### ISSUE TITLE
IMPROVED README WITH IMAGES

### ISSUE THREAD

**Issue by M-PRERNA** [srimani-programmer/Breast-Cancer-Predictor#1]
Hello maintainers !!!
We can improve the readme with some images and stats.
If you feel so, then please assign this issue to me!!!

**Comment by srimani-programmer** [comment]
@M-PRERNA Assigned this issue to you. please proceed with it.

**Comment by M-PRERNA** [comment]
Sure I'll make the PR soon.

**Comment by M-PRERNA** [comment]
Heyy !!! had few doubts, where can I connect with you?

**Comment by srimani-programmer** [comment]
send me your queries to my mail id: srimanikantapalakollu@gmail.com or else ping me on whatsapp: 9912575995

**Comment by M-PRERNA** [comment]
ok sure, sir !!!

**Comment by M-PRERNA** [comment]
@srimani-programmer This issue is still open, do I need to make more changes?

**Comment by srimani-programmer** [comment]
Sorry, @M-PRERNA forgot to close this issue.
