### ISSUE TITLE
Wrong file name in the project according to its use case

### ISSUE THREAD

**Issue by Priyanshu078** [srimani-programmer/Breast-Cancer-Predictor#100]
the header file is named footer.html
footer.html should be header.html
![image](https://user-images.githubusercontent.com/66347715/112743372-59e50a80-8fb4-11eb-8fd7-37cd9df57073.png)

**Comment by Priyanshu078** [comment]
Please assign me this issue
I am a GSSOC participant

**Comment by vardhan-scripter** [comment]
Please raise issues on new_pipeline branch. Don't touch master branch.
