### ISSUE TITLE
[Gssoc'21] Back to top button

### ISSUE THREAD

**Issue by arpit456jain** [srimani-programmer/Breast-Cancer-Predictor#103]
I want to add a back to top button at the bottom.
@srimani-programmer Kindly assign it to me.

**Comment by srimani-programmer** [comment]
@arpit456jain issue is assigned to you.

**Comment by arpit456jain** [comment]
@srimani-programmer favicon is missing because of which it is giving an error which will effect the speed of website
<img width="960" alt="11" src="https://user-images.githubusercontent.com/55352601/113409299-9e1a4580-93ce-11eb-8653-142cbe35fa39.png">

Can I add a favicon??

**Comment by arpit456jain** [comment]
@srimani-programmer kindly review my PR #107

**Comment by einhawking** [comment]
I am a participant GSSOC'21
I would like to contribute in this

**Comment by arpit456jain** [comment]
@einhawking i am sorry but i had already done this and opened a PR.
