### ISSUE TITLE
Dark-Mode with toggle button.

### ISSUE THREAD

**Issue by arpit456jain** [srimani-programmer/Breast-Cancer-Predictor#104]
I want to add the dark mode in the website with a toggle button through which user can switch between light and dark mode

**Comment by srimani-programmer** [comment]
@arpit456jain please go with the issue.

**Comment by arpit456jain** [comment]
@srimani-programmer the CSS is hard-code (inline CSS) dark mode can not be added until CSS is internal or external 
I mean all CSS should be in a style tag or in a separate file style.css then only I can write CSS for dark mode.
Can I make a required changes in CSS.??

**Comment by einhawking** [comment]
I am a participant GSSOC'21
I would like to contribute in this

**Comment by arpit456jain** [comment]
@einhawking i am sorry this issue is already assigned to me
