### ISSUE TITLE
back to top button in new Pipeline

### ISSUE THREAD

**Issue by arpit456jain** [srimani-programmer/Breast-Cancer-Predictor#121]
back to top button in new Pipeline

**Comment by arpit456jain** [comment]
@srimani-programmer kindly assign me this 
i am creating the PR

**Comment by srimanikantapalakollu** [comment]
@arpit456jain issue is assigned to you.

**Comment by arpit456jain** [comment]
@srimani-programmer there is already a back to top button there 😅

**Comment by arpit456jain** [comment]
its position is little bit wrong i am making it correct

**Comment by arpit456jain** [comment]
@srimani-programmer I am closing this issue as there is already a back to top button 

and 

 I just change 20px to 15px and it is showing merge conflicts 
leave it

 thank you for giving me a chance.
