### ISSUE TITLE
Feature Engineering and Data Cleaning in Breast-Cancer using Numerical Data

### ISSUE THREAD

**Issue by mayank8200** [srimani-programmer/Breast-Cancer-Predictor#13]

**Comment by kritikashah20** [comment]
Can I work on this issue?

**Comment by srimani-programmer** [comment]
@kritikashah20 issue is assigned to you. You can start working on it.

**Comment by kritikashah20** [comment]
@srimani-programmer, I don't know how but in assignees my name is not visible. Will that create a problem? Can you please assign again. I have finished the task, I will create a pull request today itself.

**Comment by srimani-programmer** [comment]
@kritikashah20 It doesn't cause any issue for you Don't worry.!🙂

**Comment by kritikashah20** [comment]
@srimani-programmer  I have created a PR via a new branch "feature_engineering" after performing data analysis. Also, I have added the Cleaned dataset csv sheet. Please review my PR and suggest if any changes have to be made.

**Comment by kritikashah20** [comment]
Please review my new PR and suggest changes if required.
