### ISSUE TITLE
Font Size is very big in phone view 

### ISSUE THREAD

**Issue by arpit456jain** [srimani-programmer/Breast-Cancer-Predictor#141]
Font Size is very big in phone view 
<img width="960" alt="font" src="https://user-images.githubusercontent.com/55352601/117840217-95544380-b299-11eb-9356-0b9912d4a2d9.png">

**Comment by arpit456jain** [comment]
and this should be in  little bit center 
<img width="960" alt="skld" src="https://user-images.githubusercontent.com/55352601/117840408-c16fc480-b299-11eb-865c-81fdd204b133.png">

**Comment by arpit456jain** [comment]
and There is lot of un-necessary space

**Comment by srimanikantapalakollu** [comment]
@arpit456jain issue is assigned to you. Please Optimise that issue.

**Comment by arpit456jain** [comment]
@srimani-programmer i am working on optimising the font size in this issue .

**Comment by arpit456jain** [comment]
@srimani-programmer why you closed  this issue ?

**Comment by arpit456jain** [comment]
@srimani-programmer this issue is not completed i think you close it by mistake
