### ISSUE TITLE
New And better Meet the Contributors! Section

### ISSUE THREAD

**Issue by arpit456jain** [srimani-programmer/Breast-Cancer-Predictor#142]
I can make a way better Meet the Contributors! Section which contains some cool hover effects

**Comment by srimanikantapalakollu** [comment]
@arpit456jain please work with the task. The issue is assigned to you.

**Comment by arpit456jain** [comment]
Level 0 ?? Seriously ? Is it a level 0 issue? @srimani-programmer

**Comment by srimanikantapalakollu** [comment]
Don't worry about the level based on your contribution I'll change the level. because most of the contributors are spamming that's why I'm not giving high levels before work.

**Comment by arpit456jain** [comment]
ok i will do it
