### ISSUE TITLE
Adding 404 error handling code and 404.html page

### ISSUE THREAD

**Issue by arpit456jain** [srimani-programmer/Breast-Cancer-Predictor#145]

**Comment by arpit456jain** [comment]
@srimani-programmer can i work on this issue?

**Comment by arpit456jain** [comment]
@srimani-programmer

**Comment by srimanikantapalakollu** [comment]
@arpit456jain please work on it.

**Comment by arpit456jain** [comment]
@srimani-programmer i will do it . Just try to review it asap because tomorrow is last date of GSSoC'21

**Comment by srimanikantapalakollu** [comment]
Okay
