### ISSUE TITLE
Save the Model as Pickle format. 

### ISSUE THREAD

**Issue by CRYPTOcoderAS** [srimani-programmer/Breast-Cancer-Predictor#153]
Consumes less storage and computation time.
Easy to deploy also using flask and Heroku
@srimani-programmer plz assign this issue to me

**Comment by ishikagoel5628** [comment]
@srimani-programmer please assign this issue to me as I have worked on this before

**Comment by prabhashkumar11** [comment]
Hi, I am Gssoc participant, I would like to work on this issue.

**Comment by AniruddhA-Omni** [comment]
I can easily do this part. Can you assign this issue to me?

**Comment by freny24** [comment]
@prabhashkumar11 you have been assigned this issue on fcfs basis. Kindly work on it!

**Comment by prabhashkumar11** [comment]
i have done, but i am facing problem in uploading on github.
