### ISSUE TITLE
Data Wastage

### ISSUE THREAD

**Issue by Krish2208** [srimani-programmer/Breast-Cancer-Predictor#155]
Hello I am a GSSoC22 Contributor. 

In the current implementation after testing the data on the 80-20 split, only 80% data is utilized for predicting the newer value leading a 20% wastage, instead after testing the data with 80-20 and setting up the hyperparameter accordingly, we can predict the new data by fitting the model again on the complete 100% data which will increase the accuracy and leading to minimal data wastage.

I would like to work on this issue. Please assign the issue to me.

**Comment by freny24** [comment]
@Krish2208 issue has been assigned to you. Kindly work on it!
