### ISSUE TITLE
docs: Add Pull Request Template 

### ISSUE THREAD

**Issue by Pradumnasaraf** [srimani-programmer/Breast-Cancer-Predictor#157]
### Chnages 
- Adding a PR template
- Template path **`.github/PULL_REQUEST_TEMPLATE.md`**

### Template Preview (while creating a PR.)
![Screenshot from 2022-03-01 17-54-32](https://user-images.githubusercontent.com/51878265/156168840-66822d65-3e60-4026-8064-f967d66cf94b.png)

#### Due to that we are also missing out on some checks on the community standards checklist

![Screenshot from 2022-03-01 21-22-52](https://user-images.githubusercontent.com/51878265/156202133-61c6d0e1-1426-4584-8051-df66a6bc45e8.png)

- Contribution towards GSsoc`22, Thank you

**Comment by maityamit** [comment]
@Pradumnasaraf I want to work this issue under **GSSoC'22**. 👋
Please assign me.

**Comment by Pradumnasaraf** [comment]
Sorry, I am also a contributor, you can find some other issues to contribute to:).

**Comment by Pradumnasaraf** [comment]
> @Pradumnasaraf I want to work this issue under **GSSoC'22**. 👋
> Please assign me. 

Sorry, I am also a contributor, you can find some other issues to contribute to:).

**Comment by Pradumnasaraf** [comment]
@vanshhhhh Can you please review this PR

**Comment by Pradumnasaraf** [comment]
@freny24 @vanshhhhh Can you please review this PR
