### ISSUE TITLE
docs: Add Issue Templates

### ISSUE THREAD

**Issue by Pradumnasaraf** [srimani-programmer/Breast-Cancer-Predictor#158]
### Chnages 
- Adding Issue templates
- Template path **`.github/ISSUE_TEMPLATE`**

###Template Types
![Screenshot from 2022-03-01 21-03-49](https://user-images.githubusercontent.com/51878265/156198784-b2e8d551-3df4-4aff-a7c7-051a88c344c0.png)

### Template Preview (while creating an issue - bug.)
![Screenshot from 2022-03-01 18-03-48](https://user-images.githubusercontent.com/51878265/156169861-53b91128-a1aa-4751-805e-affb8a4924a3.png)

####  Due to that we are also missing out on some checks on the community standards checklist

![Screenshot from 2022-03-01 21-22-52](https://user-images.githubusercontent.com/51878265/156202336-fabaad4b-137b-473d-ab7f-4492033f5eef.png)

- Contribution towards GSsoc`22, Thank you

**Comment by Charu2510** [comment]
@srimani-programmer Can i contribute in this? I am just a beginner.

**Comment by maityamit** [comment]
@srimani-programmer I want to work in this issue under **GSSoC'22** . 
Please assign me .

**Comment by Pradumnasaraf** [comment]
@Charu2510 @maityamit, As per Gssoc you have to open an issue for yourself to work on, you can find some other issues to contribute to:).
