### ISSUE TITLE
Develop a website for our application

### ISSUE THREAD

**Issue by srimani-programmer** [srimani-programmer/Breast-Cancer-Predictor#16]
**Features of the Website**

1. It should have a good looking UI.
2. It should have good responsiveness.
3. It should contain all the details regarding Breast cancer.
4. It should contain the contributor's names as well.

**Technologies Allowed**

- HTML5
- CSS3
- Javascript
- Bootstrap

**NOTE:**  No high-level frameworks like React, Angular, Vue are strictly not allowed.

**Bonus Points:** The One who develops the website with good features and responsiveness will get extra bonus points.

**Comment by anushavc** [comment]
can i work on this issue?

**Comment by srimani-programmer** [comment]
@anushavc Yeah Sure you can proceed with the work.
