### ISSUE TITLE
Model Accuracy instead of Prediction Accuracy is currently displayed.

### ISSUE THREAD

**Issue by Krish2208** [srimani-programmer/Breast-Cancer-Predictor#164]
In the current scenario, the accuracy score displayed on the results page is the accuracy of the predictor as a whole, while it should be the accuracy score of the current data provided. 

I want to work on this issue under GSSoC 22.

**Comment by freny24** [comment]
@Krish2208 issue assigned! Kindly work on it

**Comment by Krish2208** [comment]
Pull Request has been made to the issue #155. PR #168 also contains the resolution of this error.
