### ISSUE TITLE
Compare different Transfer learning method on image dataset

### ISSUE THREAD

**Issue by Keyurchaniyara** [srimani-programmer/Breast-Cancer-Predictor#199]
Hello

I am a GSSoC22 contributor. I would like to compare transfer learning method VGG16, INCEPTION V3, RESNET on image dataset. I had already worked with 3 algorithm in breast cancer detection. Please do assign this to me.

Thank You :)

**Comment by freny24** [comment]
@Keyurchaniyara  issue has been assigned to you! Good Luck!

**Comment by Keyurchaniyara** [comment]
Thank you for giving me this opportunity.

Approach:

0. Create a Jupyter file 
1. Clean the image data(remove Redundant images)
2. Data Preprocessing(data generation)
3. Create different transferlearning model
4. Show classification report
5. Plot Visualization graph
6. Compare accuracy
