### ISSUE TITLE
Create a Logo for this project

### ISSUE THREAD

**Issue by manan-bedi2908** [srimani-programmer/Breast-Cancer-Predictor#2]

**Comment by amandp13** [comment]
@manan-bedi2908 Can you please Assign me this issue as part of SWOC 2021

**Comment by srimani-programmer** [comment]
@amandp13 you are work on this issue. The Logo should be unique and follow the proper guidelines that should not harase anyone or a particular thing.

**Comment by amandp13** [comment]
Yeah, will create the PR soon, you can review that.

**Comment by amandp13** [comment]
@manan-bedi2908 @srimani-programmer  Created the PR, Do review.

**Comment by srimani-programmer** [comment]
#11 Done with the issue.
