### ISSUE TITLE
Breast Cancer Predictions using CatBoost

### ISSUE THREAD

**Issue by miretteamin** [srimani-programmer/Breast-Cancer-Predictor#213]
I want this issue to be assigned for me. Thank you!

**Comment by Shweta2024** [comment]
Hello! I'm a GSSoC'22 Contributor. I read about CatBoost and its implementation. So, I would like to contribute to this. Please assign this issue to me. 
Thank you

**Comment by freny24** [comment]
@miretteamin Please provide a proper description!

**Comment by miretteamin** [comment]
Hello, @freny24 
I used Catboost in Zindi competition: Blood Spectroscopy Classification Challenge.
So, I'm suggesting using Catboost Model developed by Yandex as it's way faster than XGboost and It performs better, and compare the model with Random Forest and Logistic Regression which are already implemented.
I want to use both datasets the numerical one and images dataset and pass both to the model, I also suggest a pre-processing technique which is the Image Moments technique in which we extract the centroids of sliced windows  that will be implemented on images dataset.

**Comment by freny24** [comment]
@miretteamin This is a great issue! Do work on it , Good Luck :)
