### ISSUE TITLE
EDA and Decision Tree Algorithm for predicting Breast Cancer

### ISSUE THREAD

**Issue by Shweta2024** [srimani-programmer/Breast-Cancer-Predictor#216]
Hello! I am a GSSoC'22 Contributor. I would like to do EDA followed by using the Decision Tree Algorithm. Please assign this task to me.
Thank you!

**Comment by freny24** [comment]
@Shweta2024 Sorry, decision tree algorithm is already covered up in another issue and it has been assigned too!
