### ISSUE TITLE
Integrate Welcome and Greeting Bot 

### ISSUE THREAD

**Issue by akrish4** [srimani-programmer/Breast-Cancer-Predictor#30]
Hi @srimani-programmer 

I would like to add a welcome bot that will greet all users who opens a issue , opens a pr and when pr gets merged 
If you feel this is a great idea let me know 
Kindly do assign me  

For reference, kindly check out: https://github.com/apps/welcome

**Comment by srimani-programmer** [comment]
@akrish4 yeah! You can proceed with your issue.

**Comment by akrish4** [comment]
Pls do assign it here in github @srimani-programmer

**Comment by srimani-programmer** [comment]
@akrish4 I already assigned it to you.

**Comment by Aayush-hub** [comment]
@srimani-programmer Can I work on it, if its still open?

**Comment by akrish4** [comment]
yes I am working on it , I was busy with my exams ..

**Comment by akrish4** [comment]
#41 PR
