### ISSUE TITLE
Add new Design at the PREDICT Area of the newely Application

### ISSUE THREAD

**Issue by srimani-programmer** [srimani-programmer/Breast-Cancer-Predictor#32]
Change the Application UI with good design at the **PREDICT Button** section.

**Comment by deytulsi18** [comment]
Can I try to do this task @srimani-programmer ?

**Comment by srimani-programmer** [comment]
Yeah.! @deytulsi18 you can work on this. I have assigned it to you.

**Comment by srimani-programmer** [comment]
@deytulsi18 Are you working on this issue?

**Comment by thesakshipandey** [comment]
Can I work on this issue?
