### ISSUE TITLE
Plot visuals of the dataset using Matplotlib, Seaborn or Plotly

### ISSUE THREAD

**Issue by manan-bedi2908** [srimani-programmer/Breast-Cancer-Predictor#35]

**Comment by Abhayraj1707** [comment]
I want to work on this issue please assign me this.

**Comment by manan-bedi2908** [comment]
@Abhayraj1707 Assigned, You can work on this issue

**Comment by kopal17** [comment]
I am interested in collaborating on this project issue. Please assign me this.

**Comment by manan-bedi2908** [comment]
@Abhayraj1707 Hi, are you currently working on this issue?

**Comment by Abhayraj1707** [comment]
> @Abhayraj1707 Hi, are you currently working on this issue?

yup, I will make pr or within 1 or 2 days

**Comment by rohansharma4050** [comment]
Hi, I am a GSSoC'21 participant and would like to work on this issue. Can you assign this to me?

**Comment by sunidhi1999-c** [comment]
I have been selected for GSSOC'21, and I am really interested in Algorithms , so I would like to contribute in this amazing repository.I can contribute for this ,I am 2 star codechef candidate and would be great to contribute to open source programs like this one. I can write these articles if given a chance.
Thanks.
Sunidhi,
3rd year,CSE at NMAMIT,Nitte,Karnatak

**Comment by sankalp-srivastava** [comment]
Please assign me to this

**Comment by virusps12** [comment]
Hello , I am interested in this issue can you please assign me this issue . I am a participant of GSSOC-21

**Comment by anjiii-18** [comment]
Hii, I am interested to work for this issue under GSSOC 2021.
