### ISSUE TITLE
New Feature Addition

### ISSUE THREAD

**Issue by MiHarsh** [srimani-programmer/Breast-Cancer-Predictor#38]
Hello Sir/ Madam,

I was wondering if I could add **Predict via Image** to this Project. Use of Computer Vision would benefit for the accuracy as well as would ease a lot in predicting. We will just need to upload an Image and get the Results. Also as it would be an addon, the initial way (random forest) would also be available as well as Predict via Image would also be functional.

Later on we can also use **meta data**(which is asked in present scenario) **with Images** to help users get much better results.

Thanks

**Comment by tiyarocks** [comment]
hey i want to work on this issue plz assign it to me

**Comment by srimani-programmer** [comment]
@MiHarsh your idea is good please make an issue with the proper name. I am closing this issue for now. please raise a new one with complete details.
