### ISSUE TITLE
Improve the documentation 

### ISSUE THREAD

**Issue by kulendu** [srimani-programmer/Breast-Cancer-Predictor#44]
Hey, @srimani-programmer I wanted to improve the documentation of this project. Adding some necessary changes, adding some **icons, gifs, images** to the documentation will make it look more appealing and easy to read for the newbies, wanted to contribute to this project.

**Comment by srimani-programmer** [comment]
@kulendu Assigning this issue to you. You can start working on this. please kindly confirm are you contributing as part of GSSOC'21?

**Comment by kulendu** [comment]
sure, I will be working on this issue (#44), and yes I would be contributing it as a part of GSSOC'21.

Thanks

**Comment by srimontidutta** [comment]
Can I contribute to this issue? (GSSoC 21)

**Comment by kulendu** [comment]
@srimani-programmer can you please make a label for GSSoC'21 here in this issue. According to the code of conduct its mandatory for the issues to be labelled as GSSoC'21 for counting the contributions

**Comment by Pavithra2206** [comment]
hi @srimani-programmer can i also be assigned this issue ? im a gssoc'21 participant

**Comment by techpkd123** [comment]
Hi @srimani-programmer can I also work upon this issue as a Gssoc'21 participant?

**Comment by Sibasish-Padhy** [comment]
Hi @srimani-programmer can I also work upon this as a Gssoc'21 participant?

**Comment by Hamza3226** [comment]
Hello, I am a GSSOC'21 participant and would like to contribute to this project.

**Comment by PSoni8** [comment]
@srimani-programmer can I also work on issue #44?
