### ISSUE TITLE
New feature

### ISSUE THREAD

**Issue by sudipg4112001** [srimani-programmer/Breast-Cancer-Predictor#46]
I would like to add a new feature to determine whether medical loan will be approved to the patients family. Using the dataset below.
https://www.kaggle.com/ninzaami/loan-predication?select=train_u6lujuX_CVtuZ9i+%281%29.csv

I am a GSSOC'21 participant

**Comment by skybluee2001** [comment]
Hii...I am a GSSOC'21 participant, and I would like to work on this issue. I have worked on a similar problem before. Kindly assign this issue to me as a part of the GSSOC'21.

**Comment by srimani-programmer** [comment]
@sudipg4112001 please raise an issue with a proper title.
