### ISSUE TITLE
Fast API based API 

### ISSUE THREAD

**Issue by VpkPrasanna** [srimani-programmer/Breast-Cancer-Predictor#48]
Instead of using Flask to serve the model in realtime @srimani-programmer , we can use something called [Fast API](https://fastapi.tiangolo.com/). With that we can able to move our builded api to production ready easily.
I have raised this issue as a part of **GSOC21**

**Comment by srimani-programmer** [comment]
@VpkPrasanna Sorry we are not planning to use FAST API right now.  please work on any other issue.
