### ISSUE TITLE
Try other ensemble models on the dataset

### ISSUE THREAD

**Issue by codeshruti** [srimani-programmer/Breast-Cancer-Predictor#49]
Use Models like XGBoost, LightGBM with Hyperparameter tuning.

I am a GSSOC'21 Participant.

**Comment by skybluee2001** [comment]
Hii...I am a GSSOC'21 participant, and I would like to work on this issue. Kindly assign this issue to me!

**Comment by anjiii-18** [comment]
Hii, I would like to work on this project under GSSOC 2021.

**Comment by Aditi0102** [comment]
Hello.... I would like to work on this project under GSSOC'21 and ensemble kNN and SVM models on the dataset and try to increase and compare the performance of the models.

**Comment by Dishita2602** [comment]
Hello ! I am GSSOC'21 participant and eagerly waiting to contribute on this project. I can use various ensemble learning models like XG Boost, AdaBoost , GBM, Random forest, Light GBM, Cat Boost and many more. I will try neat & clean code which will be very easy to understand. Kindly give me a chance !
