### ISSUE TITLE
Create an image dataset for predicting Breast-Cancer

### ISSUE THREAD

**Issue by manan-bedi2908** [srimani-programmer/Breast-Cancer-Predictor#6]

**Comment by amandp13** [comment]
@manan-bedi2908 Allow me to work on this issue [SWOC 2021]

**Comment by manan-bedi2908** [comment]
@amandp13 Assigned, go ahead!

**Comment by amandp13** [comment]
@manan-bedi2908 I have gathered Both the Image and CSV Dataset, Should I commit both?

**Comment by manan-bedi2908** [comment]
@amandp13 For now, commit only image dataset, csv dataset is already available in the repo. 
If we require csv dataset in future, we'll create another issue

**Comment by amandp13** [comment]
@manan-bedi2908 Done. Please review #15

**Comment by srimani-programmer** [comment]
#15 Done with the issue.

**Comment by srimani-programmer** [comment]
@amandp13 could you please make another PR of the image dataset to the New_pipeline branch.

**Comment by amandp13** [comment]
@srimani-programmer Okay.

**Comment by amandp13** [comment]
@srimani-programmer It is showing as follows:

On branch New_Pipeline
Your branch is up to date with 'origin/New_Pipeline'.
nothing to commit, working tree clean
