### ISSUE TITLE
Creating EDA for the problem dataset

### ISSUE THREAD

**Issue by dikshajoshi18** [srimani-programmer/Breast-Cancer-Predictor#65]
I am a GSSoC 21 participant. I can contribute to the project by creating an Exploratory Data Analysis including possible feature Engineering and plots for Breast Cancer Prediction dataset
 Kindly assign this work to me @manan-bedi2908 @srimani-programmer
DISCORD: diksha#6684

**Comment by srimani-programmer** [comment]
@dikshajoshi18 EDA is not required right now for the project.
