### ISSUE TITLE
prediction using numerical data

### ISSUE THREAD

**Issue by rohansharma4050** [srimani-programmer/Breast-Cancer-Predictor#70]
I will be using the numerical data to train my model using SVM and KNN algorithms .
I would like to work on this under GSSOC21 @srimani-programmer can you please assign this to me

**Comment by SandipPalit** [comment]
That are some of the basic ML models. Also try to think of some advanced models with better accuracy

**Comment by rohansharma4050** [comment]
@SandipPalit along with the above algorithms I can build a neural network also for the same for increasing the accuracy
