### ISSUE TITLE
Create a Logistic Regression Model for predicting Breast-Cancer using Numerical Data

### ISSUE THREAD

**Issue by manan-bedi2908** [srimani-programmer/Breast-Cancer-Predictor#8]

**Comment by Himanshi2016** [comment]
Hello Sir ! 
I want to work on this project and on this issue also but I am a beginner So will you please guide me how to start and how to solve this issue ?

**Comment by srimani-programmer** [comment]
@manan-bedi2908 please guide him with the appropriate procedue.

**Comment by manan-bedi2908** [comment]
@Himanshi2016 Hi, so basically, you have to create a Logistics Regression Model to predict the Breast Cancer first. You may select the appropriate features from the numerical data provided in the repo
For any doubts, you can ping me on slack personally Manan Bedi (M) in the Project Channel. Would be happy to help you!

**Comment by Himanshi2016** [comment]
okay sir, Thank you

**Comment by TanweerulHaque** [comment]
Hello Sir, I want to be assigned this issue and proceed with the same. I can contribute to it.

**Comment by manan-bedi2908** [comment]
@TanweerulHaque Assigned to you! Go ahead

@Himanshi2016 , you can still ask your doubt and work for creating other models. The method is generally same
