### ISSUE TITLE
Issue Template missing

### ISSUE THREAD

**Issue by Subhangini** [srimani-programmer/Breast-Cancer-Predictor#81]
Issue template is an important feature of any repo. When we create an  Issue, Issue template ask some questions related to the issue being created so that other contributors can know what the issue is and how we can solve it . This is missing in this project.

**Comment by Subhangini** [comment]
I would like to work on this issue

**Comment by srimani-programmer** [comment]
@Subhangini please provide a proper description of the issue.

**Comment by Subhangini** [comment]
Done!

**Comment by srimani-programmer** [comment]
@Subhangini issue is assigning to you. please work on it.

**Comment by Subhangini** [comment]
why you closed this issue? Your repo still doesn't contain Issue template
