### ISSUE TITLE
Pull request template missing

### ISSUE THREAD

**Issue by Subhangini** [srimani-programmer/Breast-Cancer-Predictor#82]
PR template is an important feature of any repo. When we create a PR (Pull Request),  PR template ask some conditions which are necessary to fullfill before submitting a PR. This is missing in this project.

**Comment by Subhangini** [comment]
I would like to work on this issue

**Comment by aayushi1908** [comment]
Hello.
I'm a GSSOC'21 participant and I'm eager to work on this issue. I have experience of working on ML based projects.
Thank you!

**Comment by srimani-programmer** [comment]
@Subhangini What do you mean by PR template? please add the proper description of the issue.

**Comment by Subhangini** [comment]
done

**Comment by srimani-programmer** [comment]
@Subhangini issue is assigned to you.
