### ISSUE TITLE
Visualizations for the numerical dataset

### ISSUE THREAD

**Issue by ELITA04** [srimani-programmer/Breast-Cancer-Predictor#83]
Hi, 

I am a GSSOC'21 participant and I want to work on adding visualizations for the numerical data.
I will use plotly to create interactive charts and write python scripts for the same so that it can be integrated with the application.

Thank you.

**Comment by aayushi1908** [comment]
Hello. Greetings from my side.
I'm Aayushi Bahukhandi, a participant of GSSOC'21. I would like to contribute to this issue - 'Visualizations for the numerical dataset'. As I've already worked on projects involving Python, Machine learning and Deep Learning, I'll create interactive charts using matplotlib and seaborn for visualizations of the datasets.
Also, I would create attractive plots like scatter plot, pair plot, box plot and violin plot.
I'm eager to work on this issue.
Thank you!

**Comment by sankalp-srivastava** [comment]
Hi,
I am Sankalp Srivastava and I have past experience with data visualization using python.
I am thinking to do a data analysis with pandas and draw graphs using seaborn and matplotlib.
Please assign this issue to me.
I am excited to work on this issue.
Thank you

**Comment by srimani-programmer** [comment]
@ELITA04 issue is assigned to you.!

**Comment by einhawking** [comment]
I am a participant GSSOC'21
I would like to contribute in this

**Comment by Dishita2602** [comment]
I am interest if no work done then
