### ISSUE TITLE
We can add "Get in touch section" in the footer.

### ISSUE THREAD

**Issue by ASHISH-GITHUB2495** [srimani-programmer/Breast-Cancer-Predictor#84]
**Features that we can add**
We can have a footer with Get in touch section ... you have option to fill name, email and message which will go directly to the admin.
Like the screenshot i have attach ...
if you like the idea I would like to contribute as GSSOC'21 participant.

**Comment by aayushi1908** [comment]
Hello there. I'm Aayushi, a GSSOC'21 participant. I want to work on this issue. Please assign it to me.

**Comment by srimani-programmer** [comment]
@ASHISH-GITHUB2495 where did you attached the Screenshot?

**Comment by srimani-programmer** [comment]
@ASHISH-GITHUB2495 You're inactive with this issue. closing the issue.
