### ISSUE TITLE
Deep Neural Network based classifier

### ISSUE THREAD

**Issue by sabhya19** [srimani-programmer/Breast-Cancer-Predictor#85]
Hello, I am a GSSoC'21 participant and am experienced in deep neural networks. 
The problem can be effectively solved by using a deep neural network for building the image classifier. I would like to work on this issue.

**Comment by sal-glitch** [comment]
Hey if possible can I work on this issue with you too? I am also experienced in DL and have been exploring various kinds of neural nets. I am a GSSoC participant too.

**Comment by srimani-programmer** [comment]
@sabhya19 Already some models are developed in DL. please work on some other features.
