### ISSUE TITLE
Update README.md file

### ISSUE THREAD

**Issue by aditi1403** [srimani-programmer/Breast-Cancer-Predictor#90]
I have made some grammatical edits to the README.md file. Kindly refer to PR #87

**Comment by tripathi-abhishek** [comment]
I wish to take this. Could you please assign me for this?!

**Comment by srimani-programmer** [comment]
@aditi1403 Assigned this to you.

**Comment by tripathi-abhishek** [comment]
So my PR did not get merged after all. What happened?
